services:
  # Backend API Service
  - type: web
    name: meams-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: meams_backend
    buildCommand: "pip install -r pythonrequirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://meams-frontend.onrender.com,http://localhost:3000
    healthCheckPath: /health

  # Frontend React App
  - type: web
    name: meams-frontend
    runtime: static
    region: oregon
    plan: free
    branch: main
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://meams-api.onrender.com
      - key: NODE_VERSION
        value: 18