# Exported from Render on 2025-10-21T15:20:47Z
version: "1"
services:
- type: web
  name: MEAMS
  runtime: python
  repo: https://github.com/yelcaole27/capstone_meams_yel
  plan: free
  envVars:
  - key: SECRET_KEY
    sync: false
  - key: EMAIL_FROM
    sync: false
  - key: EMAIL_PASSWORD
    sync: false
  - key: EMAIL_USERNAME
    sync: false
  - key: CORS_ORIGINS
    sync: false
  - key: ENVIRONMENT
    sync: false
  - key: API_HOST
    sync: false
  - key: API_PORT
    sync: false
  - key: DATABASE_NAME
    sync: false
  - key: MONGODB_URL
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  autoDeployTrigger: "off"
  rootDir: meams_backend
